name: secret
on: [push]
env:
  my_secret_value: ${{ secret.joy_personal }}

jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: action/checkout@v3

      - name: print secret
        run: echo "$my-secret-value"
