name: secret
on: [push]
env:
  my_secret_value: ${{ secrets.joy_personal }}

jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: print secret
        run: echo "$my-secret-value"
