name: simple commands
on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: say echo
        run: echo "hello Joyson"

      - name: show date
        run: date > joyson.txt

      - name: list files
        run: ls -la
